#!/bin/bash
#SBATCH --job-name=ShapePackOrchestrator
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
#SBATCH --time=0-00:05:00
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=ltkhg4@mst.edu
#SBATCH --export=all
#SBATCH --out=results/mill-%j.out

# Load system modules
module load anaconda/2023.07
module load gcc/12.2.0

# Load Rust environment
source "$HOME/.cargo/env"

# Navigate to repo
cd /home/ltkhg4/Code/git/shape-packing

# Activate Python environment
source .venv/bin/activate

# Execute parallel loop
python run_parallel_loop.py
